### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by i15haidah** [chrzyki/candc#1]
i tried to follow tutorial but I wasn't able to execute tokenisation.

$ bin/t working/tutorial/katebush.txt
usage: tokkie [options]

  --help
  --version
  --stdin
  --input <file>
  --output <file>
  --format <arg> (possible values: [prolog,txt], default: txt)
  --language <arg> (possible values: [en,it], default: en)
  --mode <arg> (possible values: [poor,iob,rich], default: poor)
  --quotes <arg> (possible values: [keep,delete], default: keep)
  --warnings <arg> (possible values: [true,false], default: false)

I also tried to change t to tokkie but a different error appeared.

$ bin/tokkie working/tutorial/katebush.txt
bin/tokkie: error while loading shared libraries: libswipl.so.6.6.4: cannot open shared object file: No such file or directory

I have downloaded swi-prolog.

$ ls
LICENCE-BOXER.txt  Makefile.cygwin  Makefile.macosxu  Makefile.targets  RELEASE.txt  doc           lib          working
LICENCE.txt        Makefile.deps    Makefile.mingw    Makefile.unix     a.out        grepsource    src
Makefile           Makefile.macosx  Makefile.sunos    README.md         bin          katebush.txt  swipl-devel

what should I do?

**Comment by chrzyki** [comment]
Heya,

I haven't worked with this myself in years but I'm sure we can figure something out.

- Are you using the latest 'official' stage of the code, i.e. what is C&C 2.0 here: https://github.com/chrzyki/candc/releases? Please also note the disclaimers in the release description.

- What platform are you trying to run this on (looks like Linux or OSX?)?

- I recall that SWI-Prolog was fiddly with respect to the way it had to be included in your PATH; how did you install SWI-Prolog?

I'll try and have a look at this tomorrow or over the weekend!

**Comment by i15haidah** [comment]
Hi!

  *   I don't know if it's the latest one but i cloned it from your repository. Should I download the C&C 2.0 anyway and try? Or is the one from your repository already the latest?

  *   I'm running it on Linux on Ubuntu

  *   I downloaded and installed SWI-Prolog according to it's documentation here : https://www.swi-prolog.org/build/unix.html

I'm really sorry but I'm kinda a newbie in this 'machine learning' and 'text processing' area and I just started fiddling in it for my research project. I hope it's not too much a bother. Thanks in advance for your help!
________________________________

**Comment by chrzyki** [comment]
Thanks for the explanation! Let me know if this helps; tested with Ubuntu 19.04:

- Install SWI-Prolog from the PPA (https://www.swi-prolog.org/build/PPA.txt)
- download the latest 'official' release from https://github.com/chrzyki/candc/releases/tag/v2.0
- extract & `cd candc/`
- `rm bin/tokkie` (we need to delete it because we want to link against modern SWI-Prolog libraries but our local code hasn't changed)
- `make bin/tokkie`
- `./bin/tokkie --input SOME_FILE.txt` should work.

Let me know if that helps!

And concerning this project and NLP-related tasks: while I still think that C&C, Boxer, CCG etc. are absolutely fascinating and their implementation is super cool, they're quite old and somewhat hard to get into. The stuff the Stanford NLP people offer (e.g. https://nlp.stanford.edu/software/tokenizer.shtml for tokenization) or what you get with NLTK (e.g. http://www.nltk.org/howto/tokenize.html for tokenization) or spaCy (e.g. https://spacy.io/api/tokenizer for tokenization) are more 'modern' and probably more straightforward I think. But if you're here explicitly for C&C and the CCG-goodness, fire away and I'll try my best to help you! :)

**Comment by chrzyki** [comment]
Feel free to re-open this if more help is needed.
